class House{
 late String Color;
 late String Style;
 late String Material;
 late String RoofType;
 late String FoundationType;
 late int NumberOfRooms;
 late int NumberOfFloors;
 late int NumberOfWindows;
 late int NumberOfDoors;
 late String Address;
 late String OwnerName;
 late int YearBuilt;
 late bool HasGarage;
 late bool HasGarden;
 late bool HasSwimmingPool;
 late bool HasBasement;
 late bool HasAttic;
 late bool HasFireplace;
 late bool HasBalcony;
 late bool HasAirConditioning;
 late bool HasHeating;
 late bool HasSecuritySystem;
 late bool HasSolarPanels;
 late bool HasSmartHomeFeatures;
 late bool HasParkingSpace;
 late bool HasLaundryRoom;
 late bool HasHomeOffice;
 late bool HasPlayground;
 late bool HasGym;
 late bool HasLibrary;
 late bool HasGameRoom;
 late bool HasWorkshop;
 late bool HasStorageRoom;
 late bool HasOutdoorKitchen;
 void DisplayhouseInfo(){
    print("House Information:");
    print("Color: $Color");
    print("Style: $Style");
    print("Material: $Material");
    print("Roof Type: $RoofType");
    print("Foundation Type: $FoundationType");
    print("Number of Rooms: $NumberOfRooms");
    print("Number of Floors: $NumberOfFloors");
    print("Number of Windows: $NumberOfWindows");
    print("Number of Doors: $NumberOfDoors");
    print("Address: $Address");
    print("Owner Name: $OwnerName");
    print("Year Built: $YearBuilt");
    print("Has Garage: $HasGarage");
    print("Has Garden: $HasGarden");
    print("Has Swimming Pool: $HasSwimmingPool");
    print("Has Basement: $HasBasement");
    print("Has Attic: $HasAttic");
    print("Has Fireplace: $HasFireplace");
    print("Has Balcony: $HasBalcony");
    print("Has Air Conditioning: $HasAirConditioning");
    print("Has Heating: $HasHeating");
    print("Has Security System: $HasSecuritySystem");
    print("Has Solar Panels: $HasSolarPanels");
    print("Has Smart Home Features: $HasSmartHomeFeatures");
    print("Has Parking Space: $HasParkingSpace");
    print("Has Laundry Room: $HasLaundryRoom");
    print("Has Home Office: $HasHomeOffice");
    print("Has Playground: $HasPlayground");
    print("Has Gym: $HasGym");
    print("Has Library: $HasLibrary");
    print("Has Game Room: $HasGameRoom");
    print("Has Workshop: $HasWorkshop");
    print("Has Storage Room: $HasStorageRoom");
    print("Has Outdoor Kitchen: $HasOutdoorKitchen");
 }

}

void main(){
  House myHouse = House();
  myHouse.Color = "Blue";
  myHouse.Style = "Modern";
  myHouse.Material = "Brick";
  myHouse.RoofType = "Gable";
  myHouse.FoundationType = "Concrete";
  myHouse.NumberOfRooms = 5;
  myHouse.NumberOfFloors = 2;
  myHouse.NumberOfWindows = 10;
  myHouse.NumberOfDoors = 3;
  myHouse.Address = "123 Main St, Springfield, USA";
  myHouse.OwnerName = "John Doe";
  myHouse.YearBuilt = 2020;
  myHouse.HasGarage = true;
  myHouse.HasGarden = true;
  myHouse.HasSwimmingPool = false;
  myHouse.HasBasement = true;
  myHouse.HasAttic = false;
  myHouse.HasFireplace = true;
  myHouse.HasBalcony = false;
  myHouse.HasAirConditioning = true;
  myHouse.HasHeating = true;
  myHouse.HasSecuritySystem = true;
  myHouse.HasSolarPanels = false;
  myHouse.HasSmartHomeFeatures = true;
  myHouse.HasParkingSpace = true;
  myHouse.HasLaundryRoom = true;
  myHouse.HasHomeOffice = false;
  myHouse.HasPlayground = false;
  myHouse.HasGym = false;
  myHouse.HasLibrary = false;
  myHouse.HasGameRoom = false;
  myHouse.HasWorkshop = false;
  myHouse.HasStorageRoom = true;
  myHouse.HasOutdoorKitchen = false;
  myHouse.DisplayhouseInfo();
}